# Generated by Django 4.2.7 on 2023-11-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
