# Generated by Django 4.2.7 on 2023-11-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[(4, 'Incomplete'), (5, 'Complete')]),
        ),
    ]
