# Generated by Django 4.2.7 on 2023-11-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='photo',
            new_name='image',
        ),
    ]
