# Generated by Django 4.2.7 on 2023-11-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photomodel',
            old_name='images',
            new_name='image',
        ),
    ]
