# Generated by Django 4.2.7 on 2023-11-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_alter_taskmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'High')]),
        ),
    ]
